version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
      python: 3.8
    commands:
      - echo starting
      
  build:
    commands:
      - echo deploying ${Stage}
      - chmod +x ./deploy.sh
      - ./deploy.sh -env ${Stage}

  post_build:
    commands:
      - echo Done!